name = "openhub-examples-cf-nitro-vite"
compatibility_date = "2025-12-22"
main = ".output/server/index.mjs"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "openhub-examples-test-fixture"
database_id = "2d4a9f67-35a1-46b1-90af-8e8d6d3d6abe" # Replace with your D1 database ID
preview_database_id = "2d4a9f67-35a1-46b1-90af-8e8d6d3d6abe" # Replace with your same as database_id

# KV Namespace
[[kv_namespaces]]
binding = "KV"
id = "ff3dc25b9cf54c5380a76332014bf35d" # Replace with your KV namespace ID
preview_id = "ff3dc25b9cf54c5380a76332014bf35d" # Replace with your same as id

# R2 Bucket
[[r2_buckets]]
binding = "BLOB"
bucket_name = "openhub-examples-test-fixture" # Replace with your R2 bucket name
preview_bucket_name = "openhub-examples-test-fixture" # Replace with your same as bucket_name